name: flutter_map_heatmap
description: A heatmap plugin for flutter_map
repository: https://github.com/tprebs/fluttermap_heatmap
version: 1.0.5+2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_lints: ^4.0.0